### PR TITLE
OpenAPI3 support

### LINKED ISSUE #44: Support OpenAPI3
see https://github.com/metosin/spec-tools/issues/105

### PR DESCRIPTION
**Pull request by rrudakov**
Adaptation of https://github.com/metosin/spec-tools/pull/236 for schema-tools

Resolve #44

### CODE REVIEW

**Comment by rrudakov** [comment]
Could somebody review it please?

**Comment by ikitommi** [comment]
Sorry for taking so long. Looks good, thanks!

**Comment by rrudakov** [comment]
Hello @ikitommi. Is it possible to make a release with this changes?

**Comment by miikka** [comment]
I'll try to do a release on Friday.

**Comment by miikka** [comment]
Just noticed that the build is broken in master; I'll see on Friday if I can fix it and release only if that's the case.

**Comment by rrudakov** [comment]
Hello @miikka, I've found the issue in my PR, will open PR with fix shortly.

**Comment by miikka** [comment]
@rrudakov Released in 0.12.3

**Comment by rrudakov** [comment]
Thank you @miikka !

**Pull request merged**
